ALTER TABLE IF EXISTS circular
  ADD COLUMN IF NOT EXISTS ai_processing_status VARCHAR(50) DEFAULT 'QUEUED';

CREATE TABLE IF NOT EXISTS circular_log (
  id SERIAL PRIMARY KEY,
  circular_id INTEGER REFERENCES circular(id) ON DELETE CASCADE,
  status VARCHAR(50) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
