CREATE TABLE IF NOT EXISTS audit_area (
  id SERIAL PRIMARY KEY,
  name VARCHAR(500) NOT NULL
);

ALTER TABLE compliance_task
  ADD COLUMN IF NOT EXISTS priority VARCHAR(50),
  ADD COLUMN IF NOT EXISTS risk_category VARCHAR(50),
  ADD COLUMN IF NOT EXISTS business_risk VARCHAR(50),
  ADD COLUMN IF NOT EXISTS control_risk VARCHAR(50),
  ADD COLUMN IF NOT EXISTS audit_area_id INTEGER REFERENCES audit_area(id);

INSERT INTO audit_area (id, name) VALUES (1, 'Physical cash difference with book balance') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (2, 'Denominationwise cash difference with books') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (3, 'Joint custody of cash is not maintained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (4, 'Cash not verified by Branch Manager') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (5, 'Reporting to HO not done for Cash Verification by BM') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (6, 'Cash Retention limit breach') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (7, 'Cash movement entries not recorded') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (8, 'Incomplete details in register for cash movement') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (9, 'Cash movement exceeding the Insurance limit') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (10, 'Cash movement unaccounted for 1 day or more') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (11, 'Short cash incedent') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (12, 'Unaccounted excess cash') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (13, 'Excess cash/Short cash not reported to HO') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (14, 'Late cash register not updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (15, 'Delay in accounting of late cash received from customer') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (16, 'Clean note guidelines not followed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (17, 'Regulatory non compliance for counterfeit notes') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (18, 'No conversion of soiled notes') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (19, 'No monitoring of ATM cash') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (20, 'Non compliance to Cash cabin safety measures') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (21, 'Non functioning of Cash counting machine') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (22, 'Non compliance to Cash safety measures') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (23, 'Delay in accounting of HO or Other Branch initiated transactions') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (24, 'Manual intervention in auto accounting GLs') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (25, 'Wrong accounting of clearing transactions') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (26, 'Joint Custodian information is not recorded') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (27, 'Safety measures for valuables not followed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (28, 'Differences in Gold Kalam count as per CBS and manual register') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (29, 'Custody of valuables evenif Gold loan account is closed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (30, 'No safety measures for undelivered deposit receipts and undelivered cheque books') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (31, 'Board for Facilities and services provided by Bank is not displayed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (32, 'Delay in ATM card application processing') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (33, 'Weak safety measures for ATM pins') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (34, 'ATM cards not alloted') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (35, 'No sufficient balance of Insta ATM cards') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (36, 'Delay in allocating ATM pin to customers') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (37, 'Accountability concern for unallocated ATM cards') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (38, 'Safety measures for undistributed ATM cards not present') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (39, 'Token system not in use') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (40, 'Loose internal control for Token system') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (41, 'Duplicate key set does not have all the important keys') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (42, 'Delay in duplicate key exchange') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (43, 'No saving account opened for person applying membership') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (44, 'Share Application register not updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (45, 'Delay in processing of membership application') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (46, 'Share Certificate register not updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (47, 'Non distribution of Share certificates on time') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (48, 'Pending action on members resignation') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (49, 'No access to AML system') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (50, 'Delay in actions on AML alerts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (51, 'AML Alerts are not reviewed properly') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (52, 'Information about source of cash deposits from customers is not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (53, 'GST registration numbers of customers not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (54, 'Purchases from Unregistered dealer') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (55, 'GST Invoices are not issued to customers') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (56, 'Mismatch in subledger balances') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (57, 'Abnotmal balances to deposit accounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (58, 'Transactions exceeding Sanction limit or DP limit allowed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (59, 'Loose internal control for 15G 15H forms') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (60, 'Delay in authorisation of 15G 15H forms') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (61, '15G 15H forms are not preserved upto 7 years') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (62, '15G 15H forms accepted from non eligible customers') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (63, 'Bankers cheque books not maintained in proper custody') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (64, 'Delay in Cheque book requisition for Bankers account') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (65, 'Delay in updation of authorised signatories to Banker account') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (66, 'Delay in Banker account reconciliation') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (67, 'Pending entries in Bankers reconciliation') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (68, 'Adverse entries in Bankers reconciliation') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (69, 'Delay in repayment of OD balances') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (70, 'Death Claim not in proper format') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (71, 'Death Claim processed without authority') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (72, 'Death Claims processed without settling exitsting liabilities') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (73, 'Death Claim process without verification of Death of Customter') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (74, 'Death Claim processed without returning funds to pension office') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (75, 'Death Claim process without fulfilling Court Order') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (76, 'Death Claim processed without Guardianship Certificate from Court') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (77, 'Death Claim processed without panchanama for locker items') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (78, 'Death Claim processed without obtaining KYC') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (79, 'Interest calculation on Death claim is immproper') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (80, 'Death Claim payments not recorded in register') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (81, 'Non-reporting of Death Claim payments to Head Office') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (82, 'Signatures of legal heirs are not obtained for Death Claim') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (83, 'No Concent of legal heir is taken for Death Claim') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (84, 'Signatures of Introducer/Witness not verified for Death Claim process') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (85, 'Death Claim processed without Indemnity') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (86, 'Improper execution of Indemnity Bond') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (87, 'Consent of legal heirs of deceased customer is not obtained for Death Claim payment') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (88, 'Improper documentation for Death Claims') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (89, 'Non-reporting of Death Claim documents to Head Office') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (90, 'Risk of UCIC Duplication') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (91, 'Delay in allocating UCIC') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (92, 'Delay in KYC updation by Branch') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (93, 'Risk of account opening without KYC') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (94, 'Delay in account opening') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (95, 'Transactions not restricted in KYC Non-compliant accounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (96, 'Non updation of Risk Classification of Customer') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (97, 'Non updation of KYC for KYC due customers') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (98, 'Risk of transactions in KYC non-compliant accounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (99, 'Revenue Leakage in old Recurring accounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (100, 'Poor Control on Amrut Bachat collections / transactions / commission / accounting etc') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (101, 'Poor Control on transactions in Inoperative account') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (102, 'Revenue Leakage in AS ON Renewal of Deposit / Regulatory guidelines breach') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (103, 'Poor Control on Standing Instructions given by customer') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (104, 'Poor Control on Nirantar Recurring scheme') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (105, 'No followup by Branch with customers for Matured deposits') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (106, 'Poor Control on Auto-renewal option for Fixed Deposits') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (107, 'Poor Control on Matured Deposits eligble for DEAF transfer') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (108, 'DEAF Claim payment without HO permission') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (109, 'Form 60 not obtained in case of No PAN cases') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (110, 'Followup for obtaining PAN is not done') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (111, 'Form 60 - Income Tax Guidelines not followed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (112, 'Poor Control on issue of Duplicate deposit receipts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (113, 'Poor Control on name modification requests for deposit receipts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (114, 'Gold Valuer documents not available with Branch') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (115, 'Gold Weights not renewed on time') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (116, 'LC discounting without HO permission') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (117, 'Interest Rate for LC directly decided by Branch') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (118, 'Cheque Discounting - Not presented on time for collection') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (119, 'BG not issued in Triplicates') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (120, 'BG not issued in serially numbered security forms') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (121, 'Original BG not called back on time') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (122, 'BGs issued withoout Joint authority') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (123, 'BGs not issued on non-judicial stamp paper') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (124, 'BG register is not updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (125, 'Due Date passed BGs not called back - appearing in Contingent liabilities') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (126, 'Consortium Finance - Consortium meetings are not being held regularly') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (127, 'Consortium Finance - Consortium meetings minutes are not prepared / not taken') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (128, 'Consortium Finance - Financial Information not shared with other member banks') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (129, 'Consortium Finance - Security verification reports are not on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (130, 'Consortium Finance  - Security verification reports are not on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (131, 'Depalyed initiative for CC Renewal process') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (132, 'Delay in feeding stock statements in CBS') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (133, 'Stock Statement details are not properly feed in CBS') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (134, 'No proper followup for submission of Stock Statement') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (135, 'Pledge loan - Physical verification of pledged stock is not done regularly') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (136, 'Release of Pledged Stock without payment') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (137, 'Liquid Securities (LIC/KVP/INSURANCE POLICY/SHARES ETC) - Not verified by Auditors') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (138, 'Advances granted on 80C Sheme deposit receipt') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (139, '80C Scheme deposit accepted as security') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (140, 'Pending Cash Credit renewals of Standard/Sub-standard loan accounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (141, 'Cash Credit accounts where transactions are allowed after due date') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (142, 'Cash Credit accounts out of Standard/Substandard category for which Stock statements are not received') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (143, 'No notices are send from time to time for Overdue accounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (144, 'Notice charges are charged to the account where notices are sent') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (145, 'Prime Security is not entered / not properly entered for eligible loan accounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (146, 'Collateral Security is not entered / not properly entered for eligible loan accounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (147, 'Security Values entered for accounts which are not having actual security') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (148, 'Loan accounts out of NPA where Section 60(1) MSCS ACT DECLARATION is submitted to employers but salary deductions are not received') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (149, 'No notices are send to employers for non deduction and submission of salary deductions as per Section 60(1) MSCS ACT DECLARATION') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (150, 'Suit file pending since more than one month after approval from Head Office') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (151, 'Loan accounts eligible for suit file (Doubtful Category Loan Accounts as of last March or in case of death of borrower and guarantor) ) but suits are not filed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (152, 'Pending suits for accounts where borrower or guarantor are deceased and period of six years has been passed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (153, 'Non suit filed cases for early slippage accounts having challenges in recovery') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (154, 'Information of nominees has been informed to the court before 90 days from the expiry date') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (155, 'Recovery made in the account, additional charges to be recovered etc are NOT informed to the court in time for pending award cases') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (156, 'Branch is not maintaining the Xerox copies of original documents in case of suit filed accounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (157, 'Loan document (bond) movement register not updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (158, 'Accounts which are pending for award since more than 9 months from the date of suit file') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (159, 'Discrepancies observed in the accounts opening under Decreed Scheme') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (160, 'Discrepancies observed in the calculation of interest amounts under Decreed Scheme') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (161, 'Awarded accounts are pending for transfer to SRO for recovery') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (162, 'Discrepancy observed in NPA identification process') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (163, 'Early Mortality') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (164, 'Gold Loan - Short Margin accounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (165, 'Due Date passed loan accounts secured by NSC/KVP/Shares/Insurance Policies etc.') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (166, 'FD loan - Short Margin accounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (167, 'Possession of Vehicles not taken for Overdue accounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (168, 'List of accounts which are written-off not maintained at Branch level') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (169, 'No intimations/notices are sent to concerned parties for Cheque Bounce cases') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (170, 'No Control on 138 suit cases') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (171, 'ECS Manadate register is not maintained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (172, 'ECS Mandates not processed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (173, 'Charges not levied for non receipt of funds through ECS mandates') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (174, 'Locker Available Board not present') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (175, 'No waiting list for locker maintained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (176, 'No partition available in locker room') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (177, 'Locker room is not clean') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (178, 'Electric Motor for water drain is not present in underground locker room') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (179, 'Strong room grill gate is not closed after use') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (180, 'Locker module is not live on CBS') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (181, 'Locker operations are not entered in CBS') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (182, 'Latest locker rent chart is not updated in CBS') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (183, 'Saving / Current accoutn not associated with locker') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (184, 'Fixed Deposit is not taken from locker customer') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (185, 'Vacant locker and remaining keys difference') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (186, 'Locker keys are not kept in joint custody') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (187, 'Advance locker rent not recovered') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (188, 'GST not separately charged for locker') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (189, 'Notices not sent to inoperative locker account holders') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (190, 'Locker applications and agreements are incomplete') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (191, 'Nominal membership application not taken from locker account holder') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (192, 'KYC of person authorised to operate the locker is not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (193, 'Locker name - Procedure for deletion of name is not properly followed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (194, 'KYC of locker account holders is incomplete') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (195, 'Nominations for locker account not entered in CBS') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (196, 'Locker operations allowed even if locker rent is outstanding') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (197, 'Signatures not taken / verified while allowing locker operations') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (198, 'Locker closed but locker key is not taken back') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (199, 'Found variables are not enetered in Kalam register') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (200, 'Found variables are not reported to HO / Required procedure not followed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (201, 'Clearing returned cheques are not returned to customer with memo') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (202, 'Counter Clearing - Cheques not recorded in LBC register') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (203, 'Charges not debited to parties') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (204, 'Returned cheques are not given back to customers along with memo') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (205, 'Clearing software not installed on multiple machines') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (206, 'Clearing Inward - Cheques not returned to concerned bank on time') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (207, 'Delay in sending cheques for collection') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (208, 'Long pending realisation for OBCs') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (209, 'OBC amounts not matching as per GL') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (210, 'Security System - Monitoring loopholes') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (211, 'IT registers not maintained / not updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (212, 'Hardware maintenance issues') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (213, 'IT Security issues') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (214, 'Networking issues') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (215, 'No alternate network available at Branch') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (216, 'IT Training gaps') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (217, 'Branch working hours not displayed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (218, 'Complaint box / Register not available in branch') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (219, 'Reporting on customer complaints not done on monthly basis to HO') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (220, 'List of charges not displayed on notice board') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (221, 'Deposit Interest rates are not updated on Interest rate display') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (222, 'DICGC Insurance payment receipt not displayed on notice board') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (223, 'KYC updation, Mobile Registration Boards are not not displayed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (224, 'Basic facilities for customer service not provided') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (225, 'Delay in Customer service') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (226, 'Bio-matrix machine not functioning') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (227, 'HO Circulars not filed in one place') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (228, 'HO Circulars not infored to all the staff') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (229, 'No daily checking of emails') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (230, 'Staff rotation register not maintained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (231, 'Transactions through single window concept not initiated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (232, 'Old Record not sorted by branch') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (233, 'Dress code not followed by staff') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (234, 'Co-ordination for audit is not received from staff') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (235, 'Vouchers are not stiched on daily basis') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (236, 'Delay in submission of HO statements') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (237, 'Branch cleanliness is not maintained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (238, 'All assets are not registered in Dead stock register') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (239, 'Depreciation calculations not correct') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (240, 'Vehicle RC books are not on record for Branch vehicles') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (241, 'Vehicle Insurance policies are not on record for Branch vehicles') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (242, 'Vehicle Insurance policies are expired for Branch vehicles') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (243, 'Branch Building is not recorded in Property register') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (244, 'Title deeds of branch buildings are not on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (245, 'Latest Property extracts of branch buildings are not on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (246, 'Latest Property tax receipts for branch buildings are not on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (247, 'Insurance policy for Branch buildings are not on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (248, 'Insurance policy for Branch buildings is not renewed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (249, 'Rented premises - rent is not recovered on time') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (250, 'Rented premises - rent agreement is not on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (251, 'Rent payment / taxes payment is not done on time') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (252, 'Rent payment not properly accounted') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (253, 'TDS Deduction on rent payment not proper') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (254, 'Expenses not approved by proper authority') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (255, 'Deadstock register not updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (256, 'Deadstock Register balances not matching with Deadstock GL') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (257, 'Deadstock writen off - approval not taken from HO') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (258, 'Deadstock - Asses numbering not done') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (259, 'Semi-deadstock not recorded in register') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (260, 'Deadstock items wrongly treated as Semi-deadstock') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (261, 'Deadstock capitalisation issues') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (262, 'Balance of Anamat not matching with Anamat register') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (263, 'Tasalmats given without approval from concerned authority') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (264, 'Tasalmat are not genuine for genuine reasons') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (265, 'Delay in settlement of tasalmats given') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (266, 'Fresh Tasalmats given without settlement of previously given tasalmat amounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (267, 'Tasalmat Balance not matching with Tasalmat register') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (268, 'Tasalmats pending since long time') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (269, 'Postage tasalmats not cleared on year end') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (270, 'Tasalmats given for legal expenses not intimated to HO - Legal department') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (271, 'Customer signatures not verified while initiating cheque book requests') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (272, 'Delay in initiating cheque book requestes') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (273, 'Delay in distribution of cheque books to customers') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (274, 'Delay in processing stop payment requests') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (275, 'Stop payment charges not recovered from customer') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (276, 'Stock of Stationary is not maintained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (277, 'No proper custody for unutilised stationary') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (278, 'No sufficient stock of stationary is maintained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (279, 'Mismatch in nominal membership fees received') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (280, 'Nominal membership forms are not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (281, 'Loan application register not maintained / updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (282, 'Equitable Mortgage register not maintained/ updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (283, 'Equitable Mortgage deeds along with Original title deeds are not sent to HO custody') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (284, 'Security verification register not maintained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (285, 'Mismatch in Security verification fees received') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (286, 'Insurance fall due register is not maintained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (287, 'Delay in Insurance policy renewal') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (288, 'Amrut Bachat agents - Adance/Commission register is not maintained / updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (289, 'Loans approved under BMs authority - Register not maintained / updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (290, 'Leave register not maintained / updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (291, 'Register for Bancassurance business not maintained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (292, 'Bancassurance business given by branch is not shared with Head Office') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (293, 'No active participation in Bancassurance business') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (294, 'Insurance agents are not visiting to branche with proper frequency') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (295, 'Deficiencies in service by Bancaassurance companies') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (296, 'TDS Deduction rate issue') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (297, 'Inward / Outward register not maintained / updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (298, 'Balance of Postage / Actual postage expenses are not tallied') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (299, 'Pending signature scanning of customers') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (300, 'Cash Scroll is not printed / reviewed on daily basis') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (301, 'Day Book is not printed on daily basis') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (302, 'KIRD is not printed on daily basis') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (303, 'Financial statements are not printed on weekly basis') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (304, 'Exceptional transaction report not reviewed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (305, 'Abnormal balances not reviewed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (306, 'Pending balances to control accounts') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (307, 'Audit compliances pending') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (308, 'Vehicle log book not updated') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (309, 'Vehicle servicing not done') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (310, 'Generator maintenance issues') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (311, 'Loan accounts of Borrower are not regular still loan is sanctioned') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (312, 'Loan accounts of Guarantor are not regular still guarantor is accepted') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (313, 'No Saving Current account of Borrower with Bank') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (314, 'Interest Rate not properly applied') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (315, 'Loan duration is not proper.') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (316, 'Discrepancies in nominal membership application') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (317, 'Shortfall in sharelinking') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (318, 'Approval from HO Loans is not taken for shortfall in sharelinking') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (319, 'Processing fees are not recovered in full') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (320, 'Approval from HO Loans is not taken for shortfall in processing fees') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (321, 'Approval from HO Loans is not taken for shortfall in liquid security') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (322, 'Liquid security is not lien marked') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (323, 'Loan purpose is not entered') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (324, 'Priority Sector information is not entered') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (325, 'Weaker Sector information is not entered') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (326, 'Loan sanctioned without authority') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (327, 'Valuation report of vehicle in case of loan sanctioned for old vehicle is not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (328, 'Loan sanctioned for old vehicle having make above three years') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (329, 'Old vehicle loan sanctioned above 50 percent of valuation') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (330, 'Reapproval not taken for loan disbursed after 3 months from sanction') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (331, 'Loan application form not properly filled') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (332, 'Loan agreements are not properly filled') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (333, 'Discrepancies observed in promissory note') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (334, 'TTO TCR forms are not taken on record with borrowers signature') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (335, 'Credit appraisal of borrower is not done properly') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (336, 'NOC from other local banks is not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (337, 'Discrepancies in credit appraisal and documentation') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (338, 'ECS Mandate Advance cheques are not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (339, 'Bank Name is not written on Advance Cheques') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (340, 'Section 60(1) MSCS ACT DECLARATION is not obtained or submitted') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (341, 'Needful declarations from borrower is not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (342, 'Signature of borrower is not obtained on loan sanction') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (343, 'Loan amount is not disbursed through saving current account of borrower') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (344, 'Vehicle inspection report along with vehicle photo is not on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (345, 'Adequate margin is not maintained for vehicle loan') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (346, 'HO approval for inadequate margin is not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (347, 'Direct payment to dealer is not made') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (348, 'DD not physically delivered to Vehicle dealer') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (349, 'Quotation Stamped receipts Invoice is on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (350, 'Insurance policy with adequate amount and coverage is not on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (351, 'Declaration for Insurance not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (352, 'Bank clause is not mentioned on Insurance policy') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (353, 'Insurance details are not entered in CBS') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (354, 'Loan sanctioned for private purpose and vehicle registration is for commercial purpose') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (355, 'Duplicate keys of vehicle are not obtained on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (356, 'Documentation flaws for Immovable security taken as collateral security') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (357, 'SMA declaration and Repayment Schedule is not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (358, 'Section 60(1) MSCS ACT DECLARATION Security Value is not entered in CBS') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (359, 'Signature of Borrower is not obtained on loan sanction letter') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (360, 'Life Insurance Policy of Borrower is not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (361, 'Adequate margin is not maintained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (362, 'Sanction without authority') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (363, 'Deposit receipt is not discharged') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (364, 'Deposit is not lien marked') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (365, 'Deposit receipt is not in proper custody') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (366, 'Interest on deposit is not getting transferred to FD loan account') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (367, 'Interest rate is not properly applied') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (368, 'Discharged debit voucher is not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (369, 'KYC Non-Compliance') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (370, 'Undertaking for loan utilisation for the benefit of minor is not taken') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (371, 'Consent of joint depositor is not taken') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (372, 'Discrepancies in loan agreement') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (373, 'Recurring passbook is not taken on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (374, 'Section 60(1) MSCS ACT DECLARATION in case of staff loan is not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (375, 'Gold loan - sanction above 1 lakh to Nominal Member') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (376, 'Nominal Membership fee is not received') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (377, 'Gold loan security includes not eligible items as security') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (378, 'Gold loan rate not properly applied') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (379, 'Jwellery/Ornament details are not properly filled in the application form') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (380, 'Valuation of Jwellary/Ornaments are properly filled and signed by SARAF along with seal') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (381, 'Jwellary / Ornaments are not taken in joint custody') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (382, 'Security details are not entered in the manual Kalam register') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (383, 'Security details are not entered in CBS Kalam register') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (384, 'Bullet repayment declaratin is not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (385, 'Loan closed before one month, Interest for whole month is not recovered') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (386, 'Stamp expenses are not reimbursed as per Bank policy') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (387, 'Sarafi Charges are not accounted properly') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (388, 'Gold Loan - Bullet repayment - Sanction amount at ID level exceeds Rs. 2 lakhs') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (389, 'Streedhan declaration is not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (390, 'Account should be opened under Gold Bullet repayment') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (391, 'Gold Non-bullet repayment loan provided to farmer') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (392, 'Repayment capacity of borrower not confirmed') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (393, 'Security is not eligible for advance') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (394, 'Proper margin is not maintained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (395, 'Loan duration is not proper') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (396, 'Bank charge is not noted on security') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (397, 'Insurance policy is not assigned to Bank') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (398, 'Loan against shares sanctioned to Non-individual') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (399, 'Loan sanctioned exceeds maximum limit') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (400, 'Valuation of Shares for granting loan against shares is not done') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (401, 'D-Mat account extract is not taken on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (402, 'Breach in per acre lending limit') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (403, 'Cultivation (LAGAN) slips from sugar factory is not taken on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (404, 'Lien mark on property is not done') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (405, 'NOC from vikas society is not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (406, 'Declarations are not obtained.') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (407, 'Cattle loan given to non-eligible animal') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (408, 'Purchase bill is not on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (409, 'Vvaternity Doctors certificate about fitness of animal is not on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (410, 'Discrepancies in Insurance Policy') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (411, 'Cattle photo not on record') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (412, 'Declarations are not obtained') ON CONFLICT DO NOTHING;
INSERT INTO audit_area (id, name) VALUES (413, 'Security inspection is not done by BM') ON CONFLICT DO NOTHING;
