CREATE TABLE IF NOT EXISTS task_header (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE compliance_task
ADD COLUMN IF NOT EXISTS header_id INTEGER REFERENCES task_header(id) ON DELETE SET NULL;
