CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE IF EXISTS compliance_task
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  ADD COLUMN IF NOT EXISTS is_approved BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_discarded BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS parent_task_id INTEGER REFERENCES compliance_task(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS embedding vector(1536),
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS assignment
  ADD COLUMN IF NOT EXISTS review_remark TEXT,
  ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP;

ALTER TABLE IF EXISTS circular
  ADD COLUMN IF NOT EXISTS reference_no VARCHAR(255),
  ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT 'General',
  ADD COLUMN IF NOT EXISTS circular_type INTEGER DEFAULT 6,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS portal_website VARCHAR(500),
  ADD COLUMN IF NOT EXISTS is_penalty_applicable BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS penalty_amount NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS penalty_description TEXT;

CREATE TABLE IF NOT EXISTS assignment_task (
  id SERIAL PRIMARY KEY,
  assignment_id INTEGER REFERENCES assignment(id) ON DELETE CASCADE,
  task_id INTEGER REFERENCES compliance_task(id) ON DELETE CASCADE,
  status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  completed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (assignment_id, task_id)
);

ALTER TABLE IF EXISTS evidence
  ADD COLUMN IF NOT EXISTS assignment_task_id INTEGER REFERENCES assignment_task(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS notification (
  id SERIAL PRIMARY KEY,
  branch_id INTEGER REFERENCES branch_dept(id) ON DELETE CASCADE,
  user_id VARCHAR(255) REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
